import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { DarkModeProvider } from "./_context/DarkModeContext";
import { ActiveSectionContextProvider } from "./_context/ActiveSectionContext";

const roboto = Roboto({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--fontFamily_Poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-gray-50`}>
        <ActiveSectionContextProvider>
          <DarkModeProvider>{children}</DarkModeProvider>
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
